version: '3'

services:
  hiddify:
    image: hiddify
    build: .
    ports:
      - 30443:443
      - 30080:80
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    volumes:
       - ./hiddify-panel/hiddifypanel.db:/opt/hiddify-config/hiddify-panel/hiddifypanel.db
       - ./ssl/:/opt/hiddify-config/ssl/
